'use strict';

// GERADO POR tools/build-rules.mjs A PARTIR DE src/filters/sources/cosmetic.txt
// Não edite à mão: npm run lint falha se este arquivo divergir da fonte.

globalThis.GuardiaoCosmeticData = Object.freeze({
    "generic": [
        ".OUTBRAIN",
        ".adsbygoogle",
        ".adsbygoogle-noablate",
        ".mgbox",
        ".rc-widget",
        ".revcontent-strip",
        ".trc_rbox_container",
        ".trc_related_container",
        "[aria-label=\"advertisement\" i]",
        "[aria-label=\"publicidade\" i]",
        "[data-ad-manager-id]",
        "[data-ad-targeting]",
        "[data-ad-unit-path]",
        "[data-adunit]",
        "[data-adunitid]",
        "[data-google-query-id]",
        "[data-testid=\"advertisement\"]",
        "[data-widget-id^=\"OUTBRAIN\"]",
        "[id^=\"M\"][id$=\"ScriptRootC\"]",
        "[id^=\"outbrain_widget_\"]",
        "[id^=\"pb-slot\"]",
        "[id^=\"prebid-\"]",
        "[id^=\"taboola-\"]",
        "div[class^=\"adSlot\"]",
        "div[id^=\"ad-slot-\"]",
        "div[id^=\"adslot-\"]",
        "div[id^=\"div-gpt-ad\"]",
        "div[id^=\"google_ads_iframe_\"]",
        "iframe[id^=\"google_ads_iframe_\"]",
        "iframe[name^=\"google_ads_iframe_\"]",
        "iframe[src*=\"adform.net\"]",
        "iframe[src*=\"adnxs.com\"]",
        "iframe[src*=\"adsterra.com\"]",
        "iframe[src*=\"amazon-adsystem.com\"]",
        "iframe[src*=\"criteo.com\"]",
        "iframe[src*=\"doubleclick.net\"]",
        "iframe[src*=\"exoclick.com\"]",
        "iframe[src*=\"googleadservices.com\"]",
        "iframe[src*=\"googlesyndication.com\"]",
        "iframe[src*=\"mgid.com\"]",
        "iframe[src*=\"openx.net\"]",
        "iframe[src*=\"outbrain.com\"]",
        "iframe[src*=\"popads.net\"]",
        "iframe[src*=\"pubmatic.com\"]",
        "iframe[src*=\"revcontent.com\"]",
        "iframe[src*=\"rubiconproject.com\"]",
        "iframe[src*=\"smartadserver.com\"]",
        "iframe[src*=\"taboola.com\"]",
        "iframe[src*=\"teads.tv\"]",
        "ins.adsbygoogle",
        "ins[data-ad-client]",
        "ins[data-ad-slot]"
    ],
    "specific": {},
    "exceptions": {}
});
